In [1]:
import numpy as np

a= np.array([(1,2,3), (3,4,5)])
print(a[0:, 2])
print(a.sum(axis=0))
print(np.sqrt(a))
print(np.std(a))


[3 5]
[4 6 8]
[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056
